# Generated by Django 3.2.12 on 2022-03-02 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220302_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='picture',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('picture_Main_Img', models.ImageField(upload_to='images/')),
                ('users', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
